### ISSUE TITLE
Weird Exception

### ISSUE THREAD

**Issue by TheFinalJoke** [TheFinalJoke/ohmyoled#115]
INFO:2022-05-15 20:24:29,487:stocks:Getting Stock
   3:       0x5593e1b0fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0ee8113e53dd9501
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:       0x5593e37118 - core::fmt::write::hfeafa1b3f4cde44b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:       0x5593e17628 - std::io::Write::write_fmt::h8e498245d185b12b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:       0x5593e1d258 - std::sys_common::backtrace::_print::hfb8a354270630015
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:       0x5593e1d258 - std::sys_common::backtrace::print::h0f1c3f701be8c977
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:       0x5593e1d258 - std::panicking::default_hook::{{closure}}::hcaba4274d385417f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:       0x5593e1cea0 - std::panicking::default_hook::h89cecd906305ec2a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:       0x5593e1d8d8 - std::panicking::rust_panic_with_hook::haded46e2df0f4fd6
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:       0x5593e1d644 - std::panicking::begin_panic_handler::{{closure}}::he5e693fe5e4ac6b4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:       0x5593e1b5b4 - std::sys_common::backtrace::__rust_end_short_backtrace::hc44d591e7ee285ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:       0x5593e1d37c - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:       0x5593ceed40 - core::panicking::panic_fmt::hb04515a4b04219bf
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:       0x5593ceed9c - core::result::unwrap_failed::hf84f08a5e231dad5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
  16:       0x5593d08fbc - ohmyoled::main::h62b08dee9c1f6c2c
  17:       0x5593d0b9b8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a273e64d2194139
  18:       0x5593cf6814 - std::rt::lang_start::{{closure}}::h474399f9c7797346
  19:       0x5593e1a904 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hdb45ce9c36440355
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  20:       0x5593e1a904 - std::panicking::try::do_call::h7e8bb9a5488c007b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  21:       0x5593e1a904 - std::panicking::try::hcc55e9ed15610d77
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  22:       0x5593e1a904 - std::panic::catch_unwind::hcf59f097cd8ee652
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  23:       0x5593e1a904 - std::rt::lang_start_internal::{{closure}}::h8fbfb8ff9e6d08fc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  24:       0x5593e1a904 - std::panicking::try::do_call::hb9473916547b0c2e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  25:       0x5593e1a904 - std::panicking::try::hfd0be8714fe2c175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  26:       0x5593e1a904 - std::panic::catch_unwind::hd13ef362c9d4275f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  27:       0x5593e1a904 - std::rt::lang_start_internal::hb2f3ce624f838b60
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  28:       0x5593d09638 - main
  29:       0x7f908d3218 - __libc_start_main

**Comment by TheFinalJoke** [comment]
INFO:2022-05-15 20:23:59,150:weather:Running Api for Weather
2022-05-15 20:24:29,454:main: TimeMatrix rendered for 30.3167s
2022-05-15 20:24:29,457:weathermatrix: Rendering Weather Matrix
2022-05-15 20:24:29,459:weathermatrix: Loading Screen 1 of Matrix
INFO:2022-05-15 20:24:29,487:stocks:Getting Stock

**Comment by TheFinalJoke** [comment]
INFO:2022-05-27 08:05:26,915:sports:Running Sports
INFO:2022-05-27 08:05:26,918:baseball:Running baseball API
2022-05-27 08:05:32,147:main: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ohmyoled/main.py", line 148, in main_run
    _, self.poll = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/ohmyoled/matrix/sport/sportmatrix.py", line 27, in poll_api
    sport = SportTransform(await self.api.run())
  File "/usr/local/lib/python3.9/site-packages/ohmyoled/lib/sports/sports.py", line 30, in run
    api_result = await api_sports.run_api_sports()
  File "/usr/local/lib/python3.9/site-packages/ohmyoled/lib/sports/apisports/apisports.py", line 36, in run_api_sports
    sport_data = await baseball.run()
  File "/usr/local/lib/python3.9/site-packages/ohmyoled/lib/sports/apisports/baseball/baseball.py", line 86, in run
    for team in api_data['standings']['response'][0] + api_data['standings']['response'][1]
IndexError: list index out of range
2022-05-27 08:05:32,440:stockmatrix: Executor shutdown has been called
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ohmyoled/matrix/stock/stockmatrix.py", line 362, in render
    await self.render_image()
  File "/usr/local/lib/python3.9/site-packages/ohmyoled/matrix/matrix.py", line 137, in render_image
    await loop.run_in_executor(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 812, in run_in_executor
    self._check_default_executor()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 519, in _check_default_executor
    raise RuntimeError('Executor shutdown has been called')
RuntimeError: Executor shutdown has been called
2022-05-27 08:05:32,447:error: Running Error Matrix
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 645, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/main.rs:99:1
