### ISSUE TITLE
Error in OLED Matrix

### ISSUE THREAD

**Issue by TheFinalJoke** [TheFinalJoke/ohmyoled#94]
]: Traceback (most recent call last):
]:   File "main.py", line 145, in main_run
]:   File "matrix/weathermatrix.py", line 145, in render
]:   File "matrix/weathermatrix.py", line 96, in render_icon
]: UnboundLocalError: local variable 'color' referenced before assignment

**Comment by TheFinalJoke** [comment]
at the end of /boot/cmdline.txt and reboot (see README.md)
2022-01-17 21:15:15,865:main: Parsing config file
2022-01-17 21:15:15,881:main: Getting Modules
2022-01-17 21:15:15,907:main: Initalized matrixes
2022-01-17 21:15:15,915:main: Starting Matrixes...
INFO:2022-01-17 21:15:15,922:time:No Api call required for time module
INFO:2022-01-17 21:15:15,936:time:Running Module TimeMatrix
INFO:2022-01-17 21:15:16,066:weather:Running Api for Weather
2022-01-17 21:15:48,235:main: TimeMatrix rendered for 32.3124s
2022-01-17 21:15:48,251:weathermatrix: Rendering Weather Matrix
2022-01-17 21:15:48,260:weathermatrix: Loading Screen 1 of Matrix
INFO:2022-01-17 21:15:48,345:stocks:Getting Stock
2022-01-17 21:15:48,405:main: local variable 'color' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 145, in main_run
    _, self.poll = await asyncio.gather(*tasks)
  File "/home/pi/ohmyoled/matrix/weathermatrix.py", line 145, in render
    self.render_icon(api)
  File "/home/pi/ohmyoled/matrix/weathermatrix.py", line 96, in render_icon
    self.draw_text((50, 0), api.current.weather_icon.font, font, fill=color)
UnboundLocalError: local variable 'color' referenced before assignment
